---
- name: Configure and deploy web server
  become: true
  gather_facts: true
  hosts: all
  vars:
    nginx_user: "root"
    nginx_worker_processes: "auto"
    nginx_error_log: "/var/log/nginx/error.log"
    nginx_pid: "/run/nginx.pid"
    nginx_worker_connections: 768
    nginx_sendfile: "on"
    nginx_tcp_nopush: "on"
    nginx_tcp_nodelay: "on"
    nginx_keepalive_timeout: 65
    nginx_types_hash_max_size: 2048
    nginx_listen_port: 8080
    nginx_server_name: "localhost"
    INDEX_HTML_CONTENT: "Hallo World"
  roles:
    - my_webserver_role

